apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-inference-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-inference
  template:
    metadata:
      labels:
        app: ml-inference
    spec:
      containers:
      - name: ml-inference-container
        image: your-dockerhub-username/ml-inference-service:latest
        ports:
        - containerPort: 8080
