version: '3.4'

services:
  cloudcomputingproject:
    image: cloudcomputingproject
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 venv/lib/python3.11/site-packages/aiosignal/__init__.py "]
    ports:
      - 5678:5678
